name: proyecto_misti
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.12
  - ipykernel=7.1.0
  - numpy=1.26.4
  - pandas=2.3.3
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - openpyxl=3.1.5
  - fastparquet=2025.12.0
  - boruta_py=0.3
  - pip
  - pip:
      - notebook==7.5.2
